export const defaultTheme = {
  colors: {
    "base-white": "#FFFFFF",
    "base-background": "#FAFAFA",
    "base-input": "#EDEDED",
    "base-button": "#E6E5E5",
    "background-header": "#F4f4F4",
    "background-popover": "#F8F8F8",
    "base-text": "#4E4E4E",
    "base-text-gray": "#656363",
    "base-border-gray": "#686868",
    "brand-orange-dark": "#F09035",
    "brand-orange": "#E49700",
    "brand-orange-light": "rgba(253, 215, 14, 0.2);",
    "brand-orange-line": "#E8A634",
    "brand-red-dark": "#D80000",
    "brand-red": "#ED3237",

  },
  textSizes: {
    "title-title-xl": "3rem",
    "title-title-l": "2rem",
    "title-title-m": "1.5rem",
    "title-title-s": "1.2rem",
    "title-title-xs": "1.125rem",
    "text-regular-l": "1.25rem",
    "text-bold-l": "1.25rem",
    "text-regular-m": "1rem",
    "text-bold-m": "1rem",
    "text-regular-s": "0.875rem",
    "text-bold-s": "0.6rem",
    "text-regular-description":"1rem",
    "text-desktop-m":"1,75rem",
  },
  fonts: {
    regular: "'Roboto'",
  },
};